#Common
label: gitops

#Deployment
replicas: 3
image:
  repository: asia.gcr.io/robotic-charmer-371101/china_gcp_learning # 変更箇所 DOCKERHUB_REPO_NAME
  tag: 03db14277c67643307666a2ea5766c5be771bde2

imageConfig:
  pullPolicy: IfNotPresent

#Service
service_type: LoadBalancer