#Common
label: gitops

#Deployment
replicas: 3
image:
  repository: asia.gcr.io/weighty-diagram-374502/china_gcp_learning # 変更箇所 DOCKERHUB_REPO_NAME
  tag: f29b45e5c254b7b3a65813c683c6de666aa1097e

imageConfig:
  pullPolicy: IfNotPresent

#Service
service_type: LoadBalancer
